---
test:
  name: Composer Performance test
  description: This is an example Composer perf test
  clients:
    type: local
    number: 1
  rounds:
  - label: basic-sample-network
    txNumber:
    - 50
    trim: 0
    rateControl:
    - type: fixed-rate
      opts:
        tps: 10
    arguments:
      testAssets: 50
    callback: benchmark/composer/composer-samples/basic-sample-network.js
  - label: basic-sample-network
    txNumber:
    - 100
    trim: 0
    rateControl:
    - type: fixed-rate
      opts:
        tps: 20
    arguments:
      testAssets: 100
    callback: benchmark/composer/composer-samples/basic-sample-network.js
  - label: basic-sample-network
    txNumber:
    - 150
    trim: 0
    rateControl:
    - type: fixed-rate
      opts:
        tps: 30
    arguments:
      testAssets: 150
    callback: benchmark/composer/composer-samples/basic-sample-network.js
  - label: basic-sample-network
    txNumber:
    - 200
    trim: 0
    rateControl:
    - type: fixed-rate
      opts:
        tps: 40
    arguments:
      testAssets: 200
    callback: benchmark/composer/composer-samples/basic-sample-network.js
  - label: basic-sample-network
    txNumber:
    - 250
    trim: 0
    rateControl:
    - type: fixed-rate
      opts:
        tps: 50
    arguments:
      testAssets: 250
    callback: benchmark/composer/composer-samples/basic-sample-network.js
  - label: basic-sample-network
    txNumber:
    - 300
    trim: 0
    rateControl:
    - type: fixed-rate
      opts:
        tps: 60
    arguments:
      testAssets: 300
    callback: benchmark/composer/composer-samples/basic-sample-network.js
  - label: basic-sample-network
    txNumber:
    - 350
    trim: 0
    rateControl:
    - type: fixed-rate
      opts:
        tps: 70
    arguments:
      testAssets: 350
    callback: benchmark/composer/composer-samples/basic-sample-network.js
  - label: basic-sample-network
    txNumber:
    - 400
    trim: 0
    rateControl:
    - type: fixed-rate
      opts:
        tps: 80
    arguments:
      testAssets: 400
    callback: benchmark/composer/composer-samples/basic-sample-network.js
  - label: basic-sample-network
    txNumber:
    - 450
    trim: 0
    rateControl:
    - type: fixed-rate
      opts:
        tps: 90
    arguments:
      testAssets: 450
    callback: benchmark/composer/composer-samples/basic-sample-network.js
  - label: basic-sample-network
    txNumber:
    - 500
    trim: 0
    rateControl:
    - type: fixed-rate
      opts:
        tps: 100
    arguments:
      testAssets: 500
    callback: benchmark/composer/composer-samples/basic-sample-network.js
monitor:
  type:
  - docker
  - process
  docker:
    name:
    - all
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
interval: 1
