version: '2'

services:

  orderer.example.com:
    extends:
      file: docker-compose-base.yml
      service: orderer
    container_name: orderer.example.com
    ports:
      - 7050:7050
    volumes:
        - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/etc/hyperledger/msp/orderer/msp
