version: '2'

services:
  ca.org1.example.com:
    extends:
      file: docker-compose-base.yml
      service: ca
    container_name: ca.org1.example.com
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/12a8092bb50fdcab0be99bf9f270be2f5cc5866fc85645681c14bdc3da9b92a0_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    extra_hosts:
        - "orderer.example.com:172.26.5.243"
        - "ca.org1.example.com:172.26.7.211"
        - "peer0.org1.example.com:172.26.7.211"

  peer0.org1.example.com:
    extends:
      file: docker-compose-base.yml
      service: peer
    container_name: peer0.org1.example.com
    environment:
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/peer/msp
        - ./crypto-config/peerOrganizations/org1.example.com/users:/etc/hyperledger/msp/users
    extra_hosts:
        - "orderer.example.com:172.26.5.243"
        - "ca.org1.example.com:172.26.7.211"
        - "peer0.org1.example.com:172.26.7.211"

